[package]
name = "syncro"
version = "0.1.0"
authors = ["mariogmarq <mariogarciamarq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Argument parser
structopt = "0.3.21"
